language: cpp
compiler: g++

before_install:
# g++4.8.1
- if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

# clang 3.4
- if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

- sudo apt-get update -qq

install:
- ls -l /usr/bin/
# g++4.8.1
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
- if [ "$CXX" = "g++" ]; then sudo /bin/bash -e 'cd /usr/bin/; for i in `ls -l |grep -- -4.6 |grep ^l |sed -e "s;.*201[0-9] ;;" -e "s; -.*;;"`; do rm -f $i; ln -s ${i}-4.9 $i; done' ; fi

# clang 3.4
- if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
- if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi

# gdb
- sudo apt-get -y install gdb

before_script: "bash -c Installation/travisCI/before_script.sh"
script: "bash -c Installation/travisCI/script.sh"
after_failure: "bash -c Installation/travisCI/after_failure.sh"
branches:
  only:
    - master
    - 1.0
    - 1.1
    - 1.2
    - 1.3
    - 1.4
    - 2.0
    - 2.1
    - 2.2
    - 2.3
    - devel

